### ISSUE TITLE
remove chrome extension icon

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/papertrail-json-parser-chrome-extension#2]
it's still hanging out there

**Comment by ondrejhlavacek** [comment]
![remove_chrome_extension_icon_ _issue__2_ _keboola_papertrail-json-parser-chrome-extension](https://cloud.githubusercontent.com/assets/497675/15205288/363ae084-1816-11e6-9a46-2caa77edeba5.png)

**Comment by odinuv** [comment]
obsolete, extension functionality is part of native papertrail
